# Generated by Django 4.1.3 on 2022-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=8)),
                ('direccion_de_envio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descipcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=8)),
            ],
        ),
    ]
