# Generated by Django 4.1.3 on 2022-11-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComercioOnline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
